name: Deploy Database

on:
  push:
    branches:
      - main  # Adjust as needed
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  uploadsqlscript:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Upload SQL script as artifact
      uses: actions/upload-artifact@v2
      with:
        name: sql-script
        path: ./sqlscripts/sqlscript.sql
  deploy:
    runs-on: ubuntu-latest
    needs: uploadsqlscript

    steps:
    - name: Download SQL script artifact
      uses: actions/download-artifact@v2
      with:
        name: sql-script
        path: ./downloaded-sqlscripts
        
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy SQL script to Azure SQL Database
      uses: azure/sql-action@v1
      with:
        server-name: "pocsqlserver00.database.windows.net"
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        sql-file: ./downloaded-sqlscripts/sqlscript.sql

    - name: Deploy SQL script
      env:
        SQL_SERVER: "pocsqlserver00.database.windows.net"
        SQL_DATABASE: "mytestdatabase"
        SQL_USER: "sysadmin"
        SQL_PASSWORD: "Finacle2024"
      run: /opt/mssql-tools/bin/sqlcmd -S $SQL_SERVER -d $SQL_DATABASE -U $SQL_USER -P $SQL_PASSWORD -i ./downloaded-sqlscripts/sqlscript.sql
